version: '3.8'

services:
  app:
    build: .
    container_name: spring_app
    ports:
      - "8080:8086"
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://karima.database.windows.net:1433;database=free-sql-db-1581137;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
      SPRING_DATASOURCE_USERNAME: Art@karima
      SPRING_DATASOURCE_PASSWORD: karima123@
      UPLOAD_DIR: /app/uploads
    volumes:
      - ./uploads:/app/uploads
